// /include/simdutf/simdutf_version.h automatically generated by release.py,
// do not change by hand
#ifndef XTEXT_SIMDUTF_XTEXT_SIMDUTF_VERSION_H
#define XTEXT_SIMDUTF_XTEXT_SIMDUTF_VERSION_H

/** The version of simdutf being used (major.minor.revision) */
#define XTEXT_SIMDUTF_VERSION "9.0.0"

namespace xtext {
enum {
  /**
   * The major version (MAJOR.minor.revision) of simdutf being used.
   */
  XTEXT_SIMDUTF_VERSION_MAJOR = 9,
  /**
   * The minor version (major.MINOR.revision) of simdutf being used.
   */
  XTEXT_SIMDUTF_VERSION_MINOR = 0,
  /**
   * The revision (major.minor.REVISION) of simdutf being used.
   */
  XTEXT_SIMDUTF_VERSION_REVISION = 0
};
} // namespace xtext

#endif // XTEXT_SIMDUTF_XTEXT_SIMDUTF_VERSION_H
