name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linux:
    uses: ./.github/workflows/linux.yml

  macos:
    uses: ./.github/workflows/macos.yml

  windows:
    uses: ./.github/workflows/windows.yml
